name: Continuos Integration

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.4
        with:
          image: pedrosilvanascimento/nodejs-workflow
          tags: ${{ github.run_number }}, ${{ steps.version.outputs.previous-version }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
