name: Continuos Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
          
      - name: install dependencies and run tests
        run: |
          npm install
          npm test
          
      # - name: Git Version
      #   id: version
      #   uses: codacy/git-version@2.7.1
      
      # - name: Docker Build & Push Action
      #   uses: mr-smithers-excellent/docker-build-push@v6.4
      #   with:
      #       image: pedrosilvanascimento/java_sem_maven
      #       tags: ${{ github.run_number }}, ${{ steps.version.outputs.previous-version }}
      #       # tags: ${{ steps.version.outputs.previous-version }}
      #       registry: docker.io
      #       dockerfile: dockerfile
      #       username: ${{secrets.DOCKER_USERNAME}}
      #       password: ${{secrets.DOCKER_PASSWORD}}
